### ISSUE TITLE
Investigate the use of Deep/Machine Learning for Traffic Light Detection.

### ISSUE THREAD

**Issue by patrobic** [patrobic/BlindAid#11]
It seems that machine/CNNs is well suited to identifying patterns/objects in images, which is basically all that we do.

Advantages:
* Requires much less CV algorithm design.
* Potentially much more reliable (fewer false positives, maybe more good positives?).
* Would bring an aspect of novelty/coolness to our project, and give us experience in ML.

Pitfalls:
* Harder to setup and configure (lack of familiarity), and higher learning curve.
* Potentially high demand in performance, maybe not suitable for embedded systems.
* Requires training process which is expensive in time/computation cost/number of images.

Conduct research to see if the foreseen advantages are realistic, and the disadvantages are manageable/not show stoppers.

**Comment by patrobic** [comment]
Mostafa, it would be good if you started work on this. A basic Blob Detection algorithm is already in place.

Two possibilities:
Replace CV Blob Detection with AI entirely (assuming it is possible to get better accuracy with AI).
Use AI as a secondary layer to confirm/reject CV Blob Detection (this may improve performance).

**Comment by mostafahammoud** [comment]
Perfect ill work on that
